name = "example_block"
description = ""
version = "0.1.0"
authors = [
    "Samuel J Palmer <sp94@users.noreply.github.com>",
]
keywords = []
categories = []

[language]
name = "Python"
version = "3.12"

[network-access]
public = false
